### PR TITLE
Encapsulation via Maybe[T]

### LINKED ISSUE #18: Encapsulate with Maybe class
I was just informed of https://github.com/mfelsche/pony-maybe which provides a convenient `Maybe` class. 

I see this currently being useful in simplifying `Alphabet`:

```pony
trait val Alphabet[L: Letter val] is Stringable
    new val create()
    fun letters(): Array[L] val
    fun parse(letter: String): (L | None)
```

to 

```pony
trait val Alphabet[L: Letter val] is Stringable
    new val create()
    fun letters(): Array[L] val
    fun parse(letter: String): Maybe[L]
```

and perhaps also for `Complement`:

```pony
interface val Complement[L: Letter val]
    fun complement(letter: L): L => letter
```

to 

```pony
interface val Complement[L: Letter val]
    fun complement(letter: L): Maybe[L] => None
```

which avoids the mistake that most letters are not self-complementing.

### PR DESCRIPTION
**Pull request by rhagenson**
Closes #18

I was able to add some encapsulation from #18, however I could not get `complement(): Maybe[Letter] => None` to compile. I really want `None` to be the default here (or some similar stand-in) hence this is a draft PR. Comments please, all are welcome!

### CODE REVIEW

**Comment by rhagenson** [comment]
I need to clean up the number of changes in this PR. I should have been branching off from master, but I was branching from the latest issue I had fixed. (Even though most of the changes here will end up on master after other PRs are accepted.)

**Comment by adri326** [comment]
Classes implementing `Alphabet` should also have their methods return `Maybe[T]` for consistency

**Comment by rhagenson** [comment]
I can get that fixed later today. Still need to try to get the complement to behave with Maybe[T] as well.

**Comment by rhagenson** [comment]
@adri326 I think this is ready to merge. What is your opinion?

Thank you for pointing out the fact that I had not applied the Maybe[T] to the implementations! That was the reason my change on complement was giving me errors -- as soon as I changed the implementations of complement to return Maybe[T] there were no errors.

**Comment by rhagenson** [comment]
BTW, in case the failing tests gave you some initial alarm (as they did for me). The failure is due to pony-bio not currently having "tests" -- i.e., no Main actor under `bio/`.

**Review by adri326 — APPROVED** [review]
Sorry for the delay, looks good!

**Pull request merged**
